
spring:
  redis:
    host: localhost
    port: 6379
    password: 123456
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    packages:
      trust-all: true    #信任所有包
    #in-memory: true  #代理
    #non-blocking-redelivery: false  #保证消息顺序性,在消息发送时候如果回滚之前，停止命令，则消息顺序不会被保存
    #send-timeout: 0   #等待消息发送时间，0代表永远
  jms:
    pub-sub-domain: true   #默认情况下activeMQ提供的是queue模式,如果选择topic(订阅)，则选择true

wx:
  appId: wx5e5f486298bca6bd
  redirectUri: https://39d7108a.ngrok.io/wx/callBack
  responseType: code
  codeUrl: https://open.weixin.qq.com/connect/oauth2/authorize
  scope: snsapi_userinfo
  accessTokenUri: https://api.weixin.qq.com/sns/oauth2/access_token
  secret: f4dd878a9f4fb7d7c44a414db3fa1fc6
  grantType: authorization_code
  userInfoUri: https://api.weixin.qq.com/sns/userinfo
  loginSuccess: www.dwlovetzp.com/wxtoken?

