eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: ascend-springcloud-zuul

server:
  port: 1998

zuul:
  routes:
    api-a:
      path: /dung/**
      serviceId: ascend-springcloud-web
